Feature 1
Balikuddembe/Personal-Portfolio pull request #1
Opened 2022-08-19 09:13 UTC by Balikuddembe

In this project,i configured linters, used Figma design to create a UI, used Flexbox to place elements in the page,Used images and backgrounds to enhance the look of this website.
For this milestone ,i have built 2 sections of the mobile website version using the template1 from Figma.The sections include:
- the toolbar 
- the headline section that is right after the header.

2022-08-19 10:57 UTC, CollinsTatang requested changes
Hi @Balikuddembe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:57 UTC, CollinsTatang commented on mobile.html
> +      <footer>
- [ ] Please remove this `footer` element from this section.

2022-08-19 10:57 UTC, CollinsTatang commented on mobile.html
> +      </h4>
- [ ] Please make use of the `h1 tag` here, since this is the main header of your page

2022-08-19 10:57 UTC, CollinsTatang commented on mobile.css
> +  height: 600px;
- [ ] Kindly change the height attribute value to `height: 618px` and work on the title text font to match the [figmal design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
### **Figmal Design**
![fig](https://user-images.githubusercontent.com/55596970/185603524-122f1e39-268e-45fa-b7e3-6e4536dbf70c.png)
### **Your Design**
![urs](https://user-images.githubusercontent.com/55596970/185603613-42ab22fa-b246-4968-b211-02cdb551a1a5.png)

2022-08-19 15:37 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @Balikuddembe , 

Great work on making the changes requested by a previous reviewer 👏👏👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No Linter issues ✔️ 
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

 ## Required Changes ♻️

- [ ] As described by the previous reviewer, you need to make sure that all font weights match the Figma design. I have explained this further in the comments below 😀

_Your design:_
![image](https://user-images.githubusercontent.com/73714615/185654648-629550b6-d34b-45fb-b04d-2802442ec2f3.png)

_Figma Design:_
![image](https://user-images.githubusercontent.com/73714615/185654746-82c39ea9-4933-49b5-8260-ce9a68968444.png)

_Check the comments under the review._

## Optional suggestions

- [ ] Kindly remove the spacing around your design 🤗 
  - _This is the default margin of the body._

![image](https://user-images.githubusercontent.com/73714615/185655280-4b3f8af8-bd0a-4bcf-93a0-af3f0ae0a3ab.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 12:52 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @Balikuddembe , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing all the required changes successfully! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 13:05 UTC, merged