Modified index.css for desktop version
Balikuddembe/Personal-Portfolio pull request #4
Opened 2022-08-25 14:44 UTC by Balikuddembe

# Hi 👋 
In this milestone_4,i have used media queries in my CSS file to ensure that my website displays correctly on a desktop version.I considered that my design matches the Figma template 1 of my choice .The break point for this version is 768px or more.I have used Grid and flex to layout the elements on the page.

2022-08-25 15:30 UTC, mukhammadrizooff requested changes
Hi @Balikuddembe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Please choose correct color `#172B4D`✔️ for `textarea`.

![image](https://user-images.githubusercontent.com/63915024/186705512-d9abaf87-f44f-4374-b8a9-f5edf4c6c70c.png)

_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] Please implement several commits! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 15:30 UTC, mukhammadrizooff commented on index.css
>    }
- [ ] [REQUIRED] Please add the `hover` effect(You need to add a border with the correct color and when hovering the card `border` should be lighting) to all cards like [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848).

![image](https://user-images.githubusercontent.com/63915024/186706375-b38d7019-04d5-4984-b9e9-db95bcfbc9ec.png)

2022-08-25 15:30 UTC, mukhammadrizooff commented on index.css
>      align-items: center;
- [ ] [REQUIRED] Your `card` elements are positioned correctly but they have some extra space errors. Please correct the errors `highlighted` in the image below:

![image](https://user-images.githubusercontent.com/63915024/186706658-04637db7-11ba-4f56-85e9-4ebe7ecb3fe9.png)

2022-08-26 12:08 UTC, Balikuddembe commented on index.css
>    }
#Hi @mukhammadrizooff 👋 
This however part on the cards, I  am supposed to do it with a coding partner as indicated in the activity of animations and transitions and it is clearly stated that i won't be reviewed by the code reviewer. Refer https://github.com/microverseinc/curriculum-html-css/blob/main/animations_exercise.md

2022-08-26 12:21 UTC, mwanawabangona approved these changes
Hi @Balikuddembe,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested changes !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 13:49 UTC, merged